baseURL = "https://holion.dk/"
languageCode = "da-dk"
defaultContentLanguage = "da"
title = "App- og webudvikler med base i Østjylland | Holion.dk"
theme = "universal"
googleAnalytics = "UA-338843-5"

[menu]

[[menu.main]]
	identifier = "home"
	name = "forside"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "services"
	name = "Ydelser"
	url = "/ydelser/"
	weight = 2

[[menu.main]]
    identifier = "apps"
    name = "Udvikling af apps"
    url = "/appudvikling/"
    weight = 1
    parent = "services"

[[menu.main]]
    identifier = "websys"
    name = "Udvikling af websystemer"
    url = "/webudvikling/"
    weight = 2
    parent = "services"

[[menu.main]]
    identifier = "drift"
    name = "Hosting og drift af apps og websystemer"
    url = "/drift/"
    weight = 3
    parent = "services"

[[menu.main]]
    identifier = "konsulent"
    name = "Konsulentassistance"
    url = "/konsulent/"
    weight = 3
    parent = "services"

[[menu.main]]
	identifier = "cases"
	name = "Cases"
	url = "/cases/"
	weight = 3

[[menu.main]]
	identifier = "about"
	name = "Om Holion"
	weight = 10

[[menu.main]]
    identifier = "jobs"
    name = "Ledige stillinger"
    url = "/ledige-stillinger/"
    parent = "about"
    weight = 1

[[menu.main]]
    identifier = "teknologi"
    name = "Teknologi"
    url = "/teknologi/"
    parent = "about"
    weight = 2

[[menu.main]]
    identifier = "fællesindsats"
    name = "Fælles indsats"
    url = "/fællesskab/"
    parent = "about"
    weight = 4

[[menu.main]]
	identifier = "contact"
	name = "Kontakt"
	url = "/kontakt/"
	parent = "about"
    weight = 100

[params]
	style = "default"

    author = "holion.dk"
    defaultKeywords = ["udvikling", "app", "web", ""]
    defaultDescription = "Specialister i apps til Android/iPhone, websystemer og automatisering af IT-processer. Se hvordan vi kan hjælpe dig her."

    logo = "/img/logo.png"
    logo_small = "/img/logo.png"

    googleMapsApiKey = "AIzaSyDIVOs27G2ngMgR84tFtaKTGsIjg70EIcc"

    about_us = "<p>IT-konsulenter med udvikling af apps, web og automatiseringsrobotter som speciale</p>"
    companyName = "Holion ApS"
    address = """<br>Østergade 4, 1.
        <br>8370 Hadsten
      """
    latitude = "56.3270084"
    longitude = "10.0484723"
    directions = "Holion ApS, Østergade 4, 1."

    mailService = "https://holionsharedfunctions.azurewebsites.net/api/contact"
    contact_form_ajax = true

[params.carousel]
    enable = true

[params.features]
    enable = true

[params.testimonials]
    enable = true
    title = "Hvad siger samarbejdspartnerne?"
    subtitle = "Vi har haft mange samarbejdspartnere og kunder gennem tiden og vi vil altid gerne høre, hvad de tænker om samarbejdet og os. Her er noget af det, de har sagt. Kontakt os for at høre mere om en eller flere specifikke kundecases."

[params.see_more]
    enable = true
    title = "Hvem er Holion?"
    subtitle = '''Holion er et konsulentfirma med speciale indenfor .NET udvikling. Vi leverer <a href="appudvikling">apps</a>, <a href="webudvikling">webløsninger</a> og programmer til virksomheder i alle størrelser, og vi er meget stolte af de mange succesfulde løsninger, som vi har leveret. Under <a href="cases">cases</a> kan du læse mere om, hvordan vi har gjort en forskel for vores kunder. Vi holder til i Hadsten, i Favrskov kommune, og hovedparten af vores kunder holder til i Østjylland - men vi har kunder over hele landet.

Vi er eksperter i det tekniske - men de specifikke detaljer behøver vi ikke kede dig med. Vi hjælper nemlig vores kunder igennem alle faser af projektet, hvor vi dækker både de tekniske og kreative aspekter, der er vigtige at tage stilling til. Vi ser frem til at løse opgaver for dig, der giver værdi både i dag og i morgen. 

Vi har kompetencerne til at vækste din forretning, og vi stræber altid efter at levere et resultat af højeste kvalitet. Fortæl os om dit behov, så kommer vi med et forslag til den løsning, som vi mener passer bedst til din forretning. <a href="kontakt">Kontakt os</a> allerede i dag!'''