baseURL = "https://holion.dk/"
languageCode = "da-dk"
defaultContentLanguage = "da"
title = "App- og webudvikler med base i Østjylland | Holion.dk"
theme = "universal"
googleAnalytics = "UA-338843-5"

[menu]

[[menu.main]]
	identifier = "services"
	name = "Ydelser"
	url = "/ydelser/"
	weight = 3

[[menu.main]]
    identifier = "apps"
    name = "Udvikling af apps"
    url = "/appudvikling/"
    weight = 1
    parent = "services"

[[menu.main]]
    identifier = "xamarin"
    name = "Konvertering af Xamarin apps"
    url = "/konvertering-af-xamarin-app/"
    weight = 2
    pre = "20px"
    parent = "services"

[[menu.main]]
    identifier = "pwa"
    name = "Alternativer til PWA"
    url = "/alternativer-til-pwa-til-ios/"
    weight = 3
    pre = "20px"
    parent = "services"

[[menu.main]]
    identifier = "websys"
    name = "Udvikling af IT-systemer"
    url = "/webudvikling/"
    weight = 4
    parent = "services"

[[menu.main]]
    identifier = "drift"
    name = "Hosting og drift"
    url = "/drift/"
    weight = 5
    parent = "services"

[[menu.main]]
	identifier = "cases"
	name = "Cases"
	url = "/cases/"
	weight = 2


[[menu.main]]
	identifier = "esg"
	name = "ESG"
	url = "/esg/"
	weight = 1

[[menu.main]]
	identifier = "holion"
	name = "Om Holion"
    url = "/holion/"
	weight = 9

[[menu.main]]
    identifier = "medarbejdere"
    name = "Medarbejdere"
    url = "/medarbejdere/"
    weight = 2
    parent = "holion"    

[[menu.main]]
    identifier = "jobs"
    name = "Ledige stillinger"
    url = "/ledige-stillinger/"
    parent = "holion"
    weight = 3

# [[menu.main]]
#     identifier = "teknologi"
#     name = "Teknologi"
#     url = "/teknologi/"
#     parent = "holion"
#     weight = 1

[[menu.main]]
	identifier = "contact"
	name = "Kontakt"
	url = "/kontakt/"
    weight = 100

[params]
	style = "default"

    author = "holion.dk"
    defaultKeywords = ["udvikling", "app", "web", ""]
    defaultDescription = "Specialister i apps til Android/iPhone, websystemer og automatisering af IT-processer. Se hvordan vi kan hjælpe dig her."

    logo = "/img/layout/holion-logo.svg"
    logo_small = "/img/layout/holion-logo.svg"

    googleMapsApiKey = "AIzaSyDIVOs27G2ngMgR84tFtaKTGsIjg70EIcc"

    about_us = """Vi udvikler apps og programmer af høj kvalitet.
    <br>vi går meget op i bæredygtighed, og har været på en 
    <br>spændende udviklingsrejse i forhold til miljø, etik og en
    <br>ny grøn profil
    """
    privatePolicy = "Når du klikker 'Kontakt mig', accepterer du også vores privatlivspolitik."
    privatePolicyLink = "/privatlivspolitik/"

    punchline = "&#8208; DET SKAL GIVE MENING!"
                    
    companyName = "Holion ApS"
    address = """<br>Vesselbjergvej 3
        <br>8370 Hadsten
      """
    latitude = "56.3287536"
    longitude = "10.0483177"
    directions = "Holion ApS, Vesselbjergvej 3"

    companyCvr = "CVR: 36 08 60 09"

    mailService = "https://holionsharedfunctions.azurewebsites.net/api/contact"
    contact_form_ajax = true

[params.carousel]
    enable = true

[params.features]
    enable = true
    title = "Din partner igennem hele udviklingsprocessen"
    description = "Holion er et IT-konsulentfirma med speciale inden for .net-udvikling. Siden 2014 har vi leveret skræddersyede apps, IT-systemer, webløsninger og programmer til virksomheder i alle størrelser. Vi er eksperter, og vi sørger for at hjælpe vores kunder igennem alle faser af et projekt, hvor vi dækker både de tekniske og kreative aspekter af processen. Vores erfaring og ekspertise sikrer dig en struktureret og gennemtænkt process, hvor slutproduktet og din tilfredshed er i højsædet. Selvom vi bare er IT-konsulenter, ser vi os selv som din partner igennem hele udviklingsprocessen, og det er lige så vigtigt for os, som for dig, at dit projekt bliver en succes. Derfor er et af nøgleordene hos Holion tillid, ordentlighed og samarbejde."
    subtitle= "Hvad skal vi hjælpe dig med?"

[params.vertical_line]
    enable = true

[params.who_is]
    enable = true    
    icon = "/img/layout/holion-logo.svg"
    title = "Hvem er Holion,"
    subtitle = "og hvad kan vi gøre for dig?"

[params.testimonials]
    enable = true
    title = "Hvad siger vores kunder?"
    buttonText = "Se flere kundecases"
    buttonLink = "/cases/"
    subtitle = "Vi har haft mange kunder gennem tiden og vi vil altid gerne høre, hvad de tænker om samarbejdet og os. Her er noget af det, de har sagt. Kontakt os for at høre mere om en eller flere specifikke kundecases."

[params.see_more]
    icon = "/img/layout/holion-circle.svg"      
    enable = true
    title = "Hvem er Holion?"
   


