baseURL = "https://holion.dk/"
languageCode = "da-dk"
defaultContentLanguage = "da"
title = "App- og webudvikler med base i Østjylland | Holion.dk"
theme = "universal"
googleAnalytics = "UA-338843-5"

[menu]

[[menu.main]]
	identifier = "home"
	name = "forside"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "services"
	name = "4X Ydelser"
	url = "/ydelser/"
	weight = 3

[[menu.main]]
    identifier = "apps"
    name = "Udvikling af apps"
    url = "/appudvikling/"
    weight = 1
    parent = "services"

[[menu.main]]
    identifier = "websys"
    name = "Udvikling af websystemer"
    url = "/webudvikling/"
    weight = 2
    parent = "services"

[[menu.main]]
    identifier = "drift"
    name = "Hosting og drift af apps og websystemer"
    url = "/drift/"
    weight = 3
    parent = "services"

[[menu.main]]
    identifier = "konsulent"
    name = "Konsulentassistance"
    url = "/konsulent/"
    weight = 3
    parent = "services"

[[menu.main]]
	identifier = "cases"
	name = "Cases"
	url = "/cases/"
	weight = 2

[[menu.main]]
    identifier = "stofa"
    name = "Stofa"
    url = "/cases/stofa/"
    weight = 1
    parent = "cases"  

[[menu.main]]
    identifier = "bescord"
    name = "Bescord"
    url = "/bescord/"
    weight = 2
    parent = "cases"      

[[menu.main]]
    identifier = "caleon"
    name = "Caleon"
    url = "/caleon/"
    weight = 3
    parent = "cases"

[[menu.main]]
    identifier = "carbuddii"
    name = "Carbuddii"
    url = "/carbuddii/"
    weight = 4
    parent = "cases"    

[[menu.main]]
    identifier = "idphotos"
    name = "Idphotos"
    url = "/idphotos/"
    weight = 5
    parent = "cases"   

    [[menu.main]]
    identifier = "improvento"
    name = "Improvento"
    url = "/improvento/"
    weight = 6
    parent = "cases"  

[[menu.main]]
	identifier = "about"
	name = "Kontakt"
	weight = 10

[[menu.main]]
	identifier = "holion"
	name = "Holion"
    url = "/holion/"
	weight = 9

[[menu.main]]
    identifier = "medarbejdere"
    name = "Medarbejdere"
    url = "/medarbejdere/"
    weight = 3
    parent = "holion"    

[[menu.main]]
    identifier = "jobs"
    name = "Ledige stillinger"
    url = "/ledige-stillinger/"
    parent = "holion"
    weight = 1

[[menu.main]]
    identifier = "teknologi"
    name = "Teknologi"
    url = "/teknologi/"
    parent = "holion"
    weight = 2

[[menu.main]]
    identifier = "fællesindsats"
    name = "Fælles indsats"
    url = "/fællesskab/"
    parent = "about"
    weight = 4

[[menu.main]]
	identifier = "contact"
	name = "Kontakt"
	url = "/kontakt/"
	parent = "about"
    weight = 100

[params]
	style = "default"

    author = "holion.dk"
    defaultKeywords = ["udvikling", "app", "web", ""]
    defaultDescription = "Specialister i apps til Android/iPhone, websystemer og automatisering af IT-processer. Se hvordan vi kan hjælpe dig her."

    logo = "/img/logo.png"
    logo_small = "/img/logo.png"

    googleMapsApiKey = "AIzaSyDIVOs27G2ngMgR84tFtaKTGsIjg70EIcc"

    about_us = """Vi udvikler apps og programmer af høj kvalitet.
    <br>vi går meget op i bæredygtighed, og har været på en 
    <br>spændende udviklingsrejse i forhold til miljø, etik og en
    <br>ny grøn profil
    """

    punchline = "&#8208; DET SKAL GIVE MENING!"
                    
    companyName = "Holion ApS"
    address = """<br>Østergade 4, 2.
        <br>8370 Hadsten
      """
    latitude = "56.3270084"
    longitude = "10.0484723"
    directions = "Holion ApS, Østergade 4, 2."

    mailService = "https://holionsharedfunctions.azurewebsites.net/api/contact"
    contact_form_ajax = true

[params.carousel]
    enable = true

[params.features]
    enable = true

[params.vertical_line]
    enable = true

[params.who_is]
    enable = true    
    icon = "/img/layout/holion-logo.svg"
    title = "Hvem er Holion,"
    subtitle = "og hvad kan vi gøre for dig?"

[params.testimonials]
    enable = true
    title = "Hvad siger kunderne?"
    subtitle = "Vi har haft mange kunder gennem tiden og vi vil altid gerne høre, hvad de tænker om samarbejdet og os. Her er noget af det, de har sagt. Kontakt os for at høre mere om en eller flere specifikke kundecases."

[params.see_more]
    icon = "/img/layout/holion-circle.svg"      
    enable = true
    title = "Hvem er Holion?"
   


